# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('shirt_number', models.CharField(max_length=2)),
                ('position', models.CharField(max_length=2)),
            ],
        ),
    ]
